frame.iseq can be nil
on C frame, frame.iseq is nil.

```
$ cat target.rb
sleep

$ exe/rdbg target.rb  -n
^C# No sourcefile available for target.rb
=>#0    [C] Kernel#sleep at target.rb:1
  #1    <main> at target.rb:1

Stop by SIGINT

(rdbg) n
["/mnt/c/ko1/src/rb/ruby-debug/lib/debug/thread_client.rb",
 598,
 #<NoMethodError: undefined method `traceable_lines_norec' for nil:NilClass>,
 ["/mnt/c/ko1/src/rb/ruby-debug/lib/debug/thread_client.rb:444:in `wait_next_action'",
  "/mnt/c/ko1/src/rb/ruby-debug/lib/debug/thread_client.rb:175:in `on_suspend'",
  "/mnt/c/ko1/src/rb/ruby-debug/lib/debug/thread_client.rb:121:in `on_trap'",
  "/mnt/c/ko1/src/rb/ruby-debug/lib/debug/session.rb:1029:in `block in console'",
  "target.rb:1:in `sleep'",
  "target.rb:1:in `<main>'"]]
Traceback (most recent call last):
        5: from target.rb:1:in `<main>'
        4: from target.rb:1:in `sleep'
        3: from /mnt/c/ko1/src/rb/ruby-debug/lib/debug/session.rb:1029:in `block in console'
        2: from /mnt/c/ko1/src/rb/ruby-debug/lib/debug/thread_client.rb:121:in `on_trap'
        1: from /mnt/c/ko1/src/rb/ruby-debug/lib/debug/thread_client.rb:175:in `on_suspend'
/mnt/c/ko1/src/rb/ruby-debug/lib/debug/thread_client.rb:444:in `wait_next_action': undefined method `traceable_lines_norec' for nil:NilClass (NoMethodError)
```