Generate line numbers for programs without them
Example message:

```
Error: test_breakpoint_execute_command_argument_correctly(DEBUGGER__::BindingBPWithCommandTest):
  RuntimeError: line numbers are required in test script. please update the script with:

     1| class Foo
     2|   def bar
     3|     binding.bp(command: "continue")
     4|     baz
     5|   end
     6|
     7|   def baz
     8|     binding.bp
     9|   end
    10| end
    11|
    12| Foo.new.bar
```