Update rake for Ruby 3.0 compatibility (#12)
```
$ bundle exec rake
Failed to remove lib/debug/debug.bundle: wrong number of arguments (given 2, expected 1)
Failed to remove tmp: wrong number of arguments (given 2, expected 1)
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
~/.gem/ruby/3.0.1/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
```

Co-authored-by: Jean Boussier <jean.boussier@gmail.com>